# .github/workflows/metrics.yml

name: GitHub Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 0 * * *"}]
  # Allows manual workflow run
  workflow_dispatch:
  # Run on pushes to main
  push: {branches: ["main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: hershiee
          template: classic
          config_timezone: Asia/Kolkata
          
          # Disabling base plugins as per your original link
          base: "" 
          
          # Enabling plugins
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: detailed
          
          plugin_discussions: yes
          plugin_discussions_categories_limit: 0
          
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_languages_categories: markup, programming
          
          plugin_lines: yes
          
          plugin_notable: yes
          plugin_notable_from: organization
